apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: ims-staging
resources:
  - ../../base
namespace: ims-staging
commonLabels:
  environment: staging
  app: ims
  part-of: inventory-management-system
  managed-by: kustomize
commonAnnotations:
  environment: staging
  description: Staging environment for Inventory Management System
  version: 1.0.0-rc
images:
  - name: ims-registry/data-ingestion-service
    newName: ims-registry/data-ingestion-service
    newTag: rc
  - name: ims-registry/calculation-service
    newName: ims-registry/calculation-service
    newTag: rc
  - name: ims-registry/workflow-service
    newName: ims-registry/workflow-service
    newTag: rc
  - name: ims-registry/api-gateway
    newName: ims-registry/api-gateway
    newTag: rc
  - name: ims-registry/websocket-service
    newName: ims-registry/websocket-service
    newTag: rc
  - name: ims-registry/monitoring-service
    newName: ims-registry/monitoring-service
    newTag: rc
  - name: ims-registry/auth-service
    newName: ims-registry/auth-service
    newTag: rc
replicas:
  - name: ims-data-ingestion-service
    count: 2
  - name: ims-calculation-service
    count: 3
  - name: ims-workflow-service
    count: 2
  - name: ims-api-gateway
    count: 2
  - name: ims-websocket-service
    count: 2
  - name: ims-monitoring-service
    count: 1
  - name: ims-auth-service
    count: 2
patchesStrategicMerge: []
configMapGenerator:
  - name: ims-common-config
    behavior: merge
    literals:
      - ENVIRONMENT=staging
      - LOG_LEVEL=INFO
      - KAFKA_BOOTSTRAP_SERVERS=kafka-headless.kafka.svc.cluster.local:9092
      - EUREKA_SERVICE_URL=http://ims-service-registry.ims-staging.svc.cluster.local:8761/eureka/
      - SERVICE_DOMAIN=ims-staging.svc.cluster.local
      - CORS_ALLOWED_ORIGINS=https://staging.ims.example.com
  - name: ims-data-ingestion-config
    behavior: merge
    literals:
      - DB_URL=jdbc:postgresql://ims-data-ingestion-db.ims-staging.svc.cluster.local:5432/ims_ingestion_staging
      - INGESTION_VALIDATION_STRICT_MODE=true
      - INGESTION_BATCH_PROCESSING_THREADS=4
  - name: ims-calculation-config
    behavior: merge
    literals:
      - DB_URL=jdbc:postgresql://ims-calculation-db.ims-staging.svc.cluster.local:5432/ims_calculation_staging
      - CALCULATION_PERFORMANCE_THREAD_POOL_SIZE=20
      - CALCULATION_PERFORMANCE_QUEUE_CAPACITY=300
  - name: ims-workflow-config
    behavior: merge
    literals:
      - DB_URL=jdbc:postgresql://ims-workflow-db.ims-staging.svc.cluster.local:5432/ims_workflow_staging
      - WORKFLOW_LOCATE_AUTO_APPROVAL_ENABLED=true
      - WORKFLOW_LOCATE_AUTO_APPROVAL_MAX_QUANTITY=500000
      - WORKFLOW_SHORT_SELL_VALIDATION_TIMEOUT_MS=200
  - name: ims-api-gateway-config
    behavior: merge
    literals:
      - RATE_LIMIT_DEFAULT_REPLENISH_RATE=5000
      - RATE_LIMIT_DEFAULT_BURST_CAPACITY=10000
  - name: ims-websocket-config
    behavior: merge
    literals:
      - WEBSOCKET_MAX_SESSIONS_PER_USER=25
  - name: ims-monitoring-config
    behavior: merge
    literals:
      - MONITORING_ALERT_ENABLED=true
      - MONITORING_ALERT_RECIPIENTS=staging-alerts@example.com
  - name: ims-auth-config
    behavior: merge
    literals:
      - DB_URL=jdbc:postgresql://ims-auth-db.ims-staging.svc.cluster.local:5432/ims_auth_staging
      - AUTH_TOKEN_ACCESS_TOKEN_VALIDITY_SECONDS=7200
      - AUTH_PASSWORD_POLICY_MIN_LENGTH=12
      - AUTH_MFA_ENABLED=true
secretGenerator:
  - name: ims-common-secrets
    behavior: merge
    type: Opaque
    literals:
      - JWT_SECRET=staging-jwt-secret-placeholder-replace-in-vault
      - ENCRYPTION_KEY=staging-encryption-key-placeholder-replace-in-vault
  - name: ims-data-ingestion-secrets
    behavior: merge
    type: Opaque
    literals:
      - DB_PASSWORD=staging-password-placeholder-replace-in-vault
      - REUTERS_API_KEY=staging-api-key-placeholder-replace-in-vault
      - REUTERS_API_SECRET=staging-api-secret-placeholder-replace-in-vault
      - BLOOMBERG_API_KEY=staging-api-key-placeholder-replace-in-vault
      - BLOOMBERG_API_SECRET=staging-api-secret-placeholder-replace-in-vault
      - MARKIT_API_KEY=staging-api-key-placeholder-replace-in-vault
      - MARKIT_API_SECRET=staging-api-secret-placeholder-replace-in-vault
      - ULTUMUS_API_KEY=staging-api-key-placeholder-replace-in-vault
      - ULTUMUS_API_SECRET=staging-api-secret-placeholder-replace-in-vault
      - RIMES_API_KEY=staging-api-key-placeholder-replace-in-vault
      - RIMES_API_SECRET=staging-api-secret-placeholder-replace-in-vault
  - name: ims-calculation-secrets
    behavior: merge
    type: Opaque
    literals:
      - DB_PASSWORD=staging-password-placeholder-replace-in-vault
      - HAZELCAST_CLUSTER_PASSWORD=staging-password-placeholder-replace-in-vault
      - REDIS_PASSWORD=staging-password-placeholder-replace-in-vault
  - name: ims-workflow-secrets
    behavior: merge
    type: Opaque
    literals:
      - DB_PASSWORD=staging-password-placeholder-replace-in-vault
      - CAMUNDA_ADMIN_PASSWORD=staging-password-placeholder-replace-in-vault
      - NOTIFICATION_SERVICE_API_KEY=staging-api-key-placeholder-replace-in-vault
  - name: ims-api-gateway-secrets
    behavior: merge
    type: Opaque
    literals:
      - RATE_LIMIT_REDIS_PASSWORD=staging-password-placeholder-replace-in-vault
  - name: ims-websocket-secrets
    behavior: merge
    type: Opaque
    literals:
      - REDIS_PASSWORD=staging-password-placeholder-replace-in-vault
  - name: ims-monitoring-secrets
    behavior: merge
    type: Opaque
    literals:
      - ALERT_SMTP_PASSWORD=staging-password-placeholder-replace-in-vault
      - PAGERDUTY_API_KEY=staging-api-key-placeholder-replace-in-vault
      - SLACK_WEBHOOK_URL=staging-webhook-url-placeholder-replace-in-vault
  - name: ims-auth-secrets
    behavior: merge
    type: Opaque
    literals:
      - DB_PASSWORD=staging-password-placeholder-replace-in-vault
      - AUTH_OAUTH2_PROVIDER_OKTA_CLIENT_SECRET=staging-client-secret-placeholder-replace-in-vault
      - AUTH_SMS_PROVIDER_API_KEY=staging-api-key-placeholder-replace-in-vault
      - AUTH_EMAIL_PROVIDER_API_KEY=staging-api-key-placeholder-replace-in-vault