apiVersion: v2
name: ims
description: Inventory Management System (IMS) for comprehensive inventory aggregation and distribution capabilities for licensed prime brokers operating across global jurisdictions
type: application
version: 1.0.0
appVersion: 1.0.0
kubeVersion: ">=1.25.0-0"
keywords:
  - inventory
  - finance
  - prime-brokerage
  - trading
  - position-management
  - calculation
home: https://github.com/example/ims
sources:
  - https://github.com/example/ims
icon: https://example.com/ims-logo.png
maintainers:
  - name: IMS Team
    email: ims-team@example.com
    url: https://example.com/ims-team
dependencies:
  - name: postgresql
    version: 12.1.3
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 17.3.14
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: kafka
    version: 20.0.5
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.enabled
  - name: elasticsearch
    version: 19.5.7
    repository: https://charts.bitnami.com/bitnami
    condition: elasticsearch.enabled
  - name: prometheus
    version: 19.6.1
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: grafana
    version: 6.50.7
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
  - name: timescaledb
    version: 0.19.0
    repository: https://charts.timescale.com
    condition: timescaledb.enabled
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/prerelease: "false"
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/operator: "false"
  artifacthub.io/operatorCapabilities: Basic Install
  artifacthub.io/category: finance