{{- /*
secret.yaml - Helm template for generating Kubernetes Secret resources for the Inventory Management System (IMS).
This template defines secret data that will be mounted into the various microservices containers,
including database credentials, API keys, encryption keys, and other sensitive information.

Secrets are defined in values.yaml and can be overridden by:
1. Custom values files
2. Environment variables
3. Helm CLI with --set flags
4. External secret management (via annotations for HashiCorp Vault integration)
*/}}

{{- /* Loop through each secret configuration defined in values.yaml */}}
{{- range $componentName, $secretConfig := .Values.secrets }}
{{- if $secretConfig.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ims.fullname" $ }}-{{ $secretConfig.name }}
  labels:
    {{- /* Common labels */}}
    app.kubernetes.io/name: {{ template "ims.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    helm.sh/chart: {{ template "ims.chart" $ }}
    app.kubernetes.io/component: {{ $secretConfig.name }}
  annotations:
    {{- /* Helm hooks ensure secrets are created before other resources that might need them */}}
    helm.sh/hook: "pre-install,pre-upgrade"
    helm.sh/hook-weight: "-5"
    
    {{- /* Optional HashiCorp Vault integration (uncomment and configure for Vault integration) */}}
    {{- if hasKey $.Values "vaultIntegration" }}
    {{- if $.Values.vaultIntegration.enabled }}
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "ims-{{ $secretConfig.name }}"
    vault.hashicorp.com/agent-pre-populate-only: "true"
    vault.hashicorp.com/agent-inject-secret-{{ $secretConfig.name }}: "ims-secrets/{{ $secretConfig.name }}"
    {{- end }}
    {{- end }}
type: Opaque
data:
  {{- range $key, $value := $secretConfig.data }}
  {{- /* 
     Each key-value pair from values.yaml becomes an entry in the Secret.
     Values are processed through Helm's template engine (tpl function) to support dynamic values,
     then base64 encoded as required by Kubernetes Secrets.
  */}}
  {{ $key }}: {{ tpl (default "" $value) $ | b64enc }}
  {{- end }}
{{- end }}
{{- end }}