apiVersion: v1
kind: ConfigMap
metadata:
  name: ims-common-config
  labels:
    app: ims
    component: common
    part-of: inventory-management-system
    managed-by: kustomize
data:
  SPRING_PROFILES_ACTIVE: k8s
  LOG_LEVEL: INFO
  KAFKA_BOOTSTRAP_SERVERS: kafka-broker:9092
  CORS_ALLOWED_ORIGINS: https://ims.example.com
  CORS_ALLOWED_METHODS: GET,POST,PUT,DELETE,OPTIONS
  CORS_ALLOWED_HEADERS: Authorization,Content-Type,X-Requested-With,Accept,X-Correlation-ID
  CORS_ALLOW_CREDENTIALS: "true"
  CORS_MAX_AGE: "3600"
  JWT_ISSUER_URI: https://auth.ims.example.com/
  JWT_AUDIENCE: ims-api
  EUREKA_SERVICE_URL: http://service-registry:8761/eureka/
  MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: "true"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info,prometheus,metrics
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: when-authorized
  JAVA_OPTS: -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Xms1g -Xmx2g -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/logs/heapdump.hprof
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ims-data-ingestion-config
  labels:
    app: ims
    component: data-ingestion-service
    part-of: inventory-management-system
    managed-by: kustomize
data:
  SERVER_PORT: "8081"
  SPRING_APPLICATION_NAME: data-ingestion-service
  DATASOURCE_URL: jdbc:postgresql://postgres:5432/ims_ingestion
  DATASOURCE_USERNAME: ims_user
  KAFKA_GROUP_ID: data-ingestion-service
  KAFKA_TOPIC_REFERENCE_DATA: reference-data
  KAFKA_TOPIC_MARKET_DATA: market-data
  KAFKA_TOPIC_TRADE_DATA: trade-data
  KAFKA_TOPIC_CONTRACT_DATA: contract-data
  KAFKA_TOPIC_MARKET_DATA_INPUT: market-data-input
  REFERENCE_DATA_BATCH_DIR: /data/reference-data/batch
  TRADE_DATA_BATCH_DIR: /data/trade-data/batch
  CONTRACT_DATA_BATCH_DIR: /data/contract-data/batch
  REUTERS_API_URL: https://api.reuters.com/data/v1
  BLOOMBERG_API_URL: https://api.bloomberg.com/data/v1
  MARKIT_API_URL: https://api.markit.com/data/v1
  ULTUMUS_API_URL: https://api.ultumus.com/data/v1
  RIMES_API_URL: https://api.rimes.com/data/v1
  REUTERS_BATCH_PATH: /data/reuters/batch
  BLOOMBERG_BATCH_PATH: /data/bloomberg/batch
  MARKIT_BATCH_PATH: /data/markit/batch
  ULTUMUS_BATCH_PATH: /data/ultumus/batch
  RIMES_BATCH_PATH: /data/rimes/batch
  APP_KAFKA_GROUP_ID: data-ingestion-service
  APP_KAFKA_TOPIC_MARKET_DATA: market-data
  APP_KAFKA_TOPIC_MARKET_DATA_INPUT: market-data-input
  INGESTION_BATCH_MAX_BATCH_SIZE: "5000"
  INGESTION_BATCH_PROCESSING_THREADS: "5"
  INGESTION_BATCH_RETRY_ATTEMPTS: "3"
  INGESTION_BATCH_RETRY_DELAY_MS: "1000"
  INGESTION_VALIDATION_ENABLED: "true"
  INGESTION_VALIDATION_STRICT_MODE: "false"
  INGESTION_SCHEDULING_REFERENCE_DATA_UPDATE: 0 0 1 * * SUN
  INGESTION_SCHEDULING_MARKET_DATA_CLEANUP: 0 0 0 * * *
  INGESTION_SCHEDULING_HEALTH_CHECK: 0 */5 * * * *
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ims-calculation-config
  labels:
    app: ims
    component: calculation-service
    part-of: inventory-management-system
    managed-by: kustomize
data:
  SERVER_PORT: "8082"
  SPRING_APPLICATION_NAME: calculation-service
  DATASOURCE_URL: jdbc:postgresql://postgres:5432/ims_calculation
  DATASOURCE_USERNAME: ims_user
  KAFKA_BOOTSTRAP_SERVERS: kafka-broker:9092
  KAFKA_CONSUMER_GROUP_ID: calculation-service
  KAFKA_TOPICS_POSITION_EVENT: position-events
  KAFKA_TOPICS_INVENTORY_EVENT: inventory-events
  KAFKA_TOPICS_MARKET_DATA_EVENT: market-data-events
  KAFKA_TOPICS_WORKFLOW_EVENT: workflow-events
  HAZELCAST_CLUSTER_NAME: ims-calculation-cluster
  HAZELCAST_INSTANCE_NAME: calculation-service
  HAZELCAST_MULTICAST_ENABLED: "false"
  HAZELCAST_TCP_IP_MEMBERS: calculation-service-0.calculation-service,calculation-service-1.calculation-service,calculation-service-2.calculation-service
  HAZELCAST_PORT: "5701"
  HAZELCAST_BACKUP_COUNT: "1"
  HAZELCAST_POSITION_MAP_TTL_SECONDS: "3600"
  HAZELCAST_INVENTORY_MAP_TTL_SECONDS: "1800"
  HAZELCAST_RULE_MAP_TTL_SECONDS: "7200"
  HAZELCAST_MAX_SIZE_PER_NODE: "10000"
  CALCULATION_POSITION_CACHE_ENABLED: "true"
  CALCULATION_POSITION_CACHE_TTL_SECONDS: "3600"
  CALCULATION_INVENTORY_CACHE_ENABLED: "true"
  CALCULATION_INVENTORY_CACHE_TTL_SECONDS: "1800"
  CALCULATION_LIMIT_CACHE_ENABLED: "true"
  CALCULATION_LIMIT_CACHE_TTL_SECONDS: "1800"
  CALCULATION_RULE_CACHE_ENABLED: "true"
  CALCULATION_RULE_CACHE_TTL_SECONDS: "7200"
  CALCULATION_PERFORMANCE_THREAD_POOL_SIZE: "20"
  CALCULATION_PERFORMANCE_QUEUE_CAPACITY: "500"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_POSITIONCALCULATION_SLIDINGWINDOWSIZE: "100"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_POSITIONCALCULATION_MINIMUMNUMBEROFCALLS: "10"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_POSITIONCALCULATION_PERMITTEDNUMBEROFCALLSINHALFOPENSTATE: "5"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_POSITIONCALCULATION_AUTOMATICTRANSITIONFROMOPENTOHALF_OPENENABLED: "true"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_POSITIONCALCULATION_WAITDURATIONINOPENSTATE: 30s
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_POSITIONCALCULATION_FAILURERATETHTHRESHOLD: "50"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_INVENTORYCALCULATION_SLIDINGWINDOWSIZE: "100"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_INVENTORYCALCULATION_MINIMUMNUMBEROFCALLS: "10"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_INVENTORYCALCULATION_PERMITTEDNUMBEROFCALLSINHALFOPENSTATE: "5"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_INVENTORYCALCULATION_AUTOMATICTRANSITIONFROMOPENTOHALF_OPENENABLED: "true"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_INVENTORYCALCULATION_WAITDURATIONINOPENSTATE: 30s
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_INVENTORYCALCULATION_FAILURERATETHTHRESHOLD: "50"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ims-workflow-config
  labels:
    app: ims
    component: workflow-service
    part-of: inventory-management-system
    managed-by: kustomize
data:
  SERVER_PORT: "8083"
  SPRING_APPLICATION_NAME: workflow-service
  DATASOURCE_URL: jdbc:postgresql://postgres:5432/ims_workflow
  DATASOURCE_USERNAME: ims_user
  KAFKA_GROUP_ID: workflow-service
  KAFKA_TOPIC_WORKFLOW_EVENT: workflow-events
  KAFKA_TOPIC_LOCATE_EVENT: locate-events
  KAFKA_TOPIC_INVENTORY_EVENT: inventory-events
  KAFKA_TOPIC_LIMIT_EVENT: limit-events
  CAMUNDA_ADMIN_USER: admin
  CALCULATION_SERVICE_URL: http://calculation-service:8082/api/v1
  WORKFLOW_ASYNC_PROCESSING_ENABLED: "true"
  WORKFLOW_LOCATE_AUTO_APPROVAL_ENABLED: "true"
  WORKFLOW_LOCATE_AUTO_APPROVAL_MAX_QUANTITY: "10000"
  WORKFLOW_LOCATE_AUTO_APPROVAL_MIN_INVENTORY_RATIO: "2.0"
  WORKFLOW_LOCATE_AUTO_APPROVAL_EXPIRY_HOURS: "24"
  WORKFLOW_LOCATE_MANUAL_REVIEW_TIMEOUT_MINUTES: "60"
  WORKFLOW_LOCATE_MANUAL_REVIEW_NOTIFICATION_ENABLED: "true"
  WORKFLOW_LOCATE_PERFORMANCE_THREAD_POOL_SIZE: "10"
  WORKFLOW_LOCATE_PERFORMANCE_QUEUE_CAPACITY: "100"
  WORKFLOW_SHORT_SELL_VALIDATION_TIMEOUT_MS: "150"
  WORKFLOW_SHORT_SELL_VALIDATION_CACHE_TTL_SECONDS: "300"
  WORKFLOW_SHORT_SELL_VALIDATION_BATCH_SIZE: "100"
  WORKFLOW_SHORT_SELL_PERFORMANCE_THREAD_POOL_SIZE: "20"
  WORKFLOW_SHORT_SELL_PERFORMANCE_QUEUE_CAPACITY: "200"
  WORKFLOW_SCHEDULING_CLEANUP_EXPIRED_LOCATES: 0 0 * * * *
  WORKFLOW_SCHEDULING_PROCESS_PENDING_VALIDATIONS: 0 */5 * * * *
  WORKFLOW_SCHEDULING_HEALTH_CHECK: 0 */5 * * * *
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_LOCATEWORKFLOW_SLIDINGWINDOWSIZE: "100"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_LOCATEWORKFLOW_MINIMUMNUMBEROFCALLS: "10"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_LOCATEWORKFLOW_PERMITTEDNUMBEROFCALLSINHALFOPENSTATE: "5"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_LOCATEWORKFLOW_AUTOMATICTRANSITIONFROMOPENTOHALF_OPENENABLED: "true"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_LOCATEWORKFLOW_WAITDURATIONINOPENSTATE: 30s
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_LOCATEWORKFLOW_FAILURERATETHTHRESHOLD: "50"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_SHORTSELLWORKFLOW_SLIDINGWINDOWSIZE: "100"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_SHORTSELLWORKFLOW_MINIMUMNUMBEROFCALLS: "10"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_SHORTSELLWORKFLOW_PERMITTEDNUMBEROFCALLSINHALFOPENSTATE: "5"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_SHORTSELLWORKFLOW_AUTOMATICTRANSITIONFROMOPENTOHALF_OPENENABLED: "true"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_SHORTSELLWORKFLOW_WAITDURATIONINOPENSTATE: 30s
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_SHORTSELLWORKFLOW_FAILURERATETHTHRESHOLD: "50"
  RESILIENCE4J_RATELIMITER_INSTANCES_SHORTSELLWORKFLOW_LIMITFORPERIOD: "1000"
  RESILIENCE4J_RATELIMITER_INSTANCES_SHORTSELLWORKFLOW_LIMITREFRESHPERIOD: 1s
  RESILIENCE4J_RATELIMITER_INSTANCES_SHORTSELLWORKFLOW_TIMEOUTDURATION: 150ms
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ims-api-gateway-config
  labels:
    app: ims
    component: api-gateway
    part-of: inventory-management-system
    managed-by: kustomize
data:
  SERVER_PORT: "8080"
  SPRING_APPLICATION_NAME: api-gateway
  SPRING_CLOUD_GATEWAY_HTTPCLIENT_CONNECT_TIMEOUT: "30000"
  SPRING_CLOUD_GATEWAY_HTTPCLIENT_RESPONSE_TIMEOUT: "30000"
  EUREKA_SERVICE_URL: http://service-registry:8761/eureka/
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  JWT_ISSUER_URI: http://auth-service:8084/auth
  JWT_JWK_SET_URI: http://auth-service:8084/auth/.well-known/jwks.json
  APP_SECURITY_CORS_ALLOWED_ORIGINS: "*"
  APP_SECURITY_CORS_ALLOWED_METHODS: GET,POST,PUT,DELETE,OPTIONS
  APP_SECURITY_CORS_ALLOWED_HEADERS: Authorization,Content-Type,X-Requested-With,Accept,X-Client-ID,X-Correlation-ID
  APP_SECURITY_CORS_ALLOW_CREDENTIALS: "true"
  APP_SECURITY_CORS_MAX_AGE: "3600"
  APP_RATE_LIMITING_ENABLED: "true"
  APP_RATE_LIMITING_KEY_RESOLVER: principalKeyResolver
  APP_RATE_LIMITING_FALLBACK_RESOLVER: ipAddressKeyResolver
  APP_TRACING_ENABLED: "true"
  APP_TRACING_CORRELATION_HEADER: X-Correlation-ID
  APP_TRACING_SAMPLING_RATE: "0.5"
  APP_LOGGING_INCLUDE_HEADERS: "true"
  APP_LOGGING_INCLUDE_BODY: "false"
  APP_LOGGING_INCLUDE_QUERY_PARAMS: "true"
  APP_SERVICES_AUTH_SERVICE_URL: lb://auth-service
  APP_SERVICES_DATA_INGESTION_SERVICE_URL: lb://data-ingestion-service
  APP_SERVICES_CALCULATION_SERVICE_URL: lb://calculation-service
  APP_SERVICES_WORKFLOW_SERVICE_URL: lb://workflow-service
  APP_SERVICES_WEBSOCKET_SERVICE_URL: lb://websocket-service
  APP_SERVICES_MONITORING_SERVICE_URL: lb://monitoring-service
  APP_SERVICES_SHORT_SELL_SERVICE_URL: lb://workflow-service
  APP_SERVICES_SHORT_SELL_SERVICE_TIMEOUT: "150"
  APP_SERVICES_SHORT_SELL_SERVICE_RETRY_ATTEMPTS: "1"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_SHORTSELLSERVICE_WAITDURATIONINOPENSTATE: 5s
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_SHORTSELLSERVICE_FAILURERATETHTHRESHOLD: "30"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_SHORTSELLSERVICE_SLIDINGWINDOWSIZE: "10"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_SHORTSELLSERVICE_MINIMUMNUMBEROFCALLS: "5"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_SHORTSELLSERVICE_PERMITTEDNUMBEROFCALLSINHALFOPENSTATE: "2"
  RESILIENCE4J_RETRY_INSTANCES_SHORTSELLSERVICE_MAXATTEMPTS: "1"
  RESILIENCE4J_RETRY_INSTANCES_SHORTSELLSERVICE_WAITDURATION: 50ms
  RESILIENCE4J_RETRY_INSTANCES_SHORTSELLSERVICE_ENABLEEXPONENTIALBACKOFF: "false"
  RESILIENCE4J_BULKHEAD_INSTANCES_SHORTSELLSERVICE_MAXCONCURRENTCALLS: "100"
  RESILIENCE4J_BULKHEAD_INSTANCES_SHORTSELLSERVICE_MAXWAITDURATION: 50ms
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ims-websocket-config
  labels:
    app: ims
    component: websocket-service
    part-of: inventory-management-system
    managed-by: kustomize
data:
  SERVER_PORT: "8085"
  SPRING_APPLICATION_NAME: websocket-service
  KAFKA_BOOTSTRAP_SERVERS: kafka-broker:9092
  KAFKA_GROUP_ID: websocket-service
  KAFKA_TOPIC_POSITION: position-events
  KAFKA_TOPIC_INVENTORY: inventory-events
  KAFKA_TOPIC_LOCATE: locate-events
  KAFKA_TOPIC_ALERT: alert-events
  JWT_ISSUER_URI: https://auth.ims.com
  JWT_AUDIENCE: ims-api
  WEBSOCKET_ALLOWED_ORIGINS: https://ims.example.com
  WEBSOCKET_SEND_TIMEOUT_MS: "15000"
  WEBSOCKET_SEND_BUFFER_SIZE_LIMIT: "524288"
  WEBSOCKET_MESSAGE_BUFFER_SIZE_LIMIT: "65536"
  APP_WEBSOCKET_CLIENT_INACTIVITY_TIMEOUT: "300000"
  APP_WEBSOCKET_MAX_SESSIONS_PER_USER: "5"
  APP_WEBSOCKET_MAX_TEXT_MESSAGE_SIZE: "65536"
  APP_WEBSOCKET_MAX_BINARY_MESSAGE_SIZE: "65536"
  APP_WEBSOCKET_HEARTBEAT_INTERVAL: "25000"
  APP_SECURITY_REQUIRED_ROLES_POSITIONS: ROLE_POSITION_VIEW
  APP_SECURITY_REQUIRED_ROLES_INVENTORY: ROLE_INVENTORY_VIEW
  APP_SECURITY_REQUIRED_ROLES_LOCATES: ROLE_LOCATE_VIEW
  APP_SECURITY_REQUIRED_ROLES_ALERTS: ROLE_ALERT_VIEW
  APP_PERFORMANCE_THREAD_POOL_SIZE: "20"
  APP_PERFORMANCE_QUEUE_CAPACITY: "500"
  APP_PERFORMANCE_MESSAGE_BATCH_SIZE: "100"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_WEBSOCKETCONNECTIONS_SLIDINGWINDOWSIZE: "100"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_WEBSOCKETCONNECTIONS_MINIMUMNUMBEROFCALLS: "10"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_WEBSOCKETCONNECTIONS_WAITDURATIONINOPENSTATE: 30s
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_WEBSOCKETCONNECTIONS_FAILURERATETHTHRESHOLD: "50"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_WEBSOCKETCONNECTIONS_PERMITTEDNUMBEROFCALLSINHALFOPENSTATE: "5"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_WEBSOCKETCONNECTIONS_AUTOMATICTRANSITIONFROMOPENTOHALF_OPENENABLED: "true"
  RESILIENCE4J_RATELIMITER_INSTANCES_WEBSOCKETCONNECTIONS_LIMITFORPERIOD: "1000"
  RESILIENCE4J_RATELIMITER_INSTANCES_WEBSOCKETCONNECTIONS_LIMITREFRESHPERIOD: 1s
  RESILIENCE4J_RATELIMITER_INSTANCES_WEBSOCKETCONNECTIONS_TIMEOUTDURATION: 0s
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ims-monitoring-config
  labels:
    app: ims
    component: monitoring-service
    part-of: inventory-management-system
    managed-by: kustomize
data:
  SERVER_PORT: "8086"
  SPRING_APPLICATION_NAME: ims-monitoring-service
  DATASOURCE_URL: jdbc:postgresql://postgres:5432/ims_monitoring
  DATASOURCE_USERNAME: ims_user
  KAFKA_BOOTSTRAP_SERVERS: kafka-broker:9092
  KAFKA_CONSUMER_GROUP_ID: ims-monitoring-service
  KAFKA_TOPICS_SYSTEM_EVENTS: ims.system.events
  KAFKA_TOPICS_ALERTS: ims.monitoring.alerts
  KAFKA_TOPICS_METRICS: ims.monitoring.metrics
  KAFKA_TOPICS_HEALTH_EVENTS: ims.monitoring.health
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  MONITORING_PROMETHEUS_STEP_SIZE: 30s
  MONITORING_METRICS_SYSTEM_COLLECTION_RATE: "15000"
  MONITORING_METRICS_SYSTEM_RETENTION_DAYS: "30"
  MONITORING_METRICS_APPLICATION_COLLECTION_RATE: "15000"
  MONITORING_METRICS_APPLICATION_RETENTION_DAYS: "30"
  MONITORING_METRICS_BUSINESS_COLLECTION_RATE: "30000"
  MONITORING_METRICS_BUSINESS_RETENTION_DAYS: "90"
  MONITORING_METRICS_DATABASE_COLLECTION_RATE: "30000"
  MONITORING_METRICS_DATABASE_RETENTION_DAYS: "30"
  MONITORING_METRICS_INTEGRATION_COLLECTION_RATE: "30000"
  MONITORING_METRICS_INTEGRATION_RETENTION_DAYS: "30"
  MONITORING_METRICS_THRESHOLD_CHECK_RATE: "60000"
  MONITORING_HEALTH_CHECK_RATE: "30000"
  MONITORING_HEALTH_SERVICE_TIMEOUT: "5000"
  MONITORING_HEALTH_DEPENDENCY_TIMEOUT: "5000"
  MONITORING_ALERTS_PROCESSING_RATE: "60000"
  MONITORING_ALERTS_METRIC_CHECK_RATE: "60000"
  MONITORING_ALERTS_HEALTH_CHECK_RATE: "60000"
  MONITORING_ALERTS_RETENTION_ACTIVE_DAYS: "14"
  MONITORING_ALERTS_RETENTION_RESOLVED_DAYS: "30"
  MONITORING_ALERTS_RETENTION_ARCHIVED_DAYS: "90"
  MONITORING_ALERTS_NOTIFICATION_CHANNELS_EMAIL_ENABLED: "true"
  MONITORING_ALERTS_NOTIFICATION_CHANNELS_EMAIL_RECIPIENTS: monitoring-team@example.com
  MONITORING_ALERTS_NOTIFICATION_CHANNELS_EMAIL_CRITICAL_RECIPIENTS: oncall@example.com
  MONITORING_ALERTS_NOTIFICATION_CHANNELS_SLACK_ENABLED: "true"
  MONITORING_ALERTS_NOTIFICATION_CHANNELS_SLACK_WEBHOOK_URL: https://hooks.slack.com/services/default/webhook/url
  MONITORING_ALERTS_NOTIFICATION_CHANNELS_SLACK_CHANNEL: "#monitoring-alerts"
  MONITORING_THRESHOLDS_SYSTEM_CPU_USAGE_WARNING: "70"
  MONITORING_THRESHOLDS_SYSTEM_CPU_USAGE_CRITICAL: "85"
  MONITORING_THRESHOLDS_SYSTEM_CPU_USAGE_DURATION: "300"
  MONITORING_THRESHOLDS_SYSTEM_MEMORY_USAGE_WARNING: "75"
  MONITORING_THRESHOLDS_SYSTEM_MEMORY_USAGE_CRITICAL: "90"
  MONITORING_THRESHOLDS_SYSTEM_MEMORY_USAGE_DURATION: "300"
  MONITORING_THRESHOLDS_SYSTEM_DISK_USAGE_WARNING: "80"
  MONITORING_THRESHOLDS_SYSTEM_DISK_USAGE_CRITICAL: "90"
  MONITORING_THRESHOLDS_SYSTEM_DISK_USAGE_DURATION: "300"
  MONITORING_THRESHOLDS_APPLICATION_RESPONSE_TIME_WARNING: "500"
  MONITORING_THRESHOLDS_APPLICATION_RESPONSE_TIME_CRITICAL: "1000"
  MONITORING_THRESHOLDS_APPLICATION_RESPONSE_TIME_DURATION: "300"
  MONITORING_THRESHOLDS_APPLICATION_ERROR_RATE_WARNING: "1"
  MONITORING_THRESHOLDS_APPLICATION_ERROR_RATE_CRITICAL: "5"
  MONITORING_THRESHOLDS_APPLICATION_ERROR_RATE_DURATION: "300"
  MONITORING_THRESHOLDS_BUSINESS_EVENT_PROCESSING_LATENCY_WARNING: "150"
  MONITORING_THRESHOLDS_BUSINESS_EVENT_PROCESSING_LATENCY_CRITICAL: "200"
  MONITORING_THRESHOLDS_BUSINESS_EVENT_PROCESSING_LATENCY_DURATION: "300"
  MONITORING_THRESHOLDS_BUSINESS_SHORT_SELL_VALIDATION_TIME_WARNING: "100"
  MONITORING_THRESHOLDS_BUSINESS_SHORT_SELL_VALIDATION_TIME_CRITICAL: "150"
  MONITORING_THRESHOLDS_BUSINESS_SHORT_SELL_VALIDATION_TIME_DURATION: "300"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ims-auth-config
  labels:
    app: ims
    component: auth-service
    part-of: inventory-management-system
    managed-by: kustomize
data:
  SERVER_PORT: "8084"
  SPRING_APPLICATION_NAME: ims-auth-service
  DATASOURCE_URL: jdbc:postgresql://postgres:5432/ims_auth
  DATASOURCE_USERNAME: ims_user
  KAFKA_BOOTSTRAP_SERVERS: kafka-broker:9092
  KAFKA_CONSUMER_GROUP_ID: auth-service
  KAFKA_TOPICS_USER_EVENTS: user-events
  KAFKA_TOPICS_AUTH_EVENTS: auth-events
  SECURITY_JWT_EXPIRATION: "3600"
  SECURITY_JWT_REFRESH_EXPIRATION: "86400"
  SECURITY_PASSWORD_HISTORY_COUNT: "24"
  SECURITY_PASSWORD_MAX_AGE_DAYS: "90"
  SECURITY_PASSWORD_MIN_LENGTH: "12"
  SECURITY_PASSWORD_COMPLEXITY_REGEX: ^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{12,}$
  SECURITY_ACCOUNT_MAX_FAILED_ATTEMPTS: "5"
  SECURITY_ACCOUNT_LOCK_DURATION_MINUTES: "30"
  SECURITY_SESSION_MAX_CONCURRENT: "3"
  SECURITY_SESSION_TIMEOUT_SECONDS: "900"
  OAUTH_CLIENT_ID: ims-client
  OAUTH_REDIRECT_URIS: https://ims.example.com/callback
  OAUTH_IDENTITY_PROVIDER_URL: https://login.microsoftonline.com/
  MFA_ENABLED: "true"
  MFA_REQUIRED_ROLES: ADMIN,COMPLIANCE_OFFICER
  MFA_TOTP_TIME_STEP_SECONDS: "30"
  MFA_TOTP_CODE_DIGITS: "6"
  MFA_TOTP_WINDOW_SIZE: "1"
  AUDIT_ENABLED: "true"
  AUDIT_EVENTS_AUTHENTICATION: "true"
  AUDIT_EVENTS_AUTHORIZATION: "true"
  AUDIT_EVENTS_USER_MANAGEMENT: "true"
  AUDIT_RETENTION_DAYS: "365"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_IDENTITYPROVIDER_SLIDINGWINDOWSIZE: "10"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_IDENTITYPROVIDER_MINIMUMNUMBEROFCALLS: "5"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_IDENTITYPROVIDER_FAILURERATETHTHRESHOLD: "50"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_IDENTITYPROVIDER_WAITDURATIONINOPENSTATE: "10000"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_IDENTITYPROVIDER_PERMITTEDNUMBEROFCALLSINHALFOPENSTATE: "3"
  RESILIENCE4J_RETRY_INSTANCES_IDENTITYPROVIDER_MAXATTEMPTS: "3"
  RESILIENCE4J_RETRY_INSTANCES_IDENTITYPROVIDER_WAITDURATION: "1000"
  RESILIENCE4J_RETRY_INSTANCES_IDENTITYPROVIDER_ENABLEEXPONENTIALBACKOFF: "true"
  RESILIENCE4J_RETRY_INSTANCES_IDENTITYPROVIDER_EXPONENTIALBACKOFFMULTIPLIER: "2"