apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: ims-base
resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - secret.yaml
commonLabels:
  app: ims
  part-of: inventory-management-system
  managed-by: kustomize
commonAnnotations:
  description: "Inventory Management System for global inventory aggregation and distribution"
  version: "1.0.0"
namePrefix: ""
nameSuffix: ""
configurations:
  - kustomizeconfig.yaml
generatorOptions:
  disableNameSuffixHash: false
  labels:
    generated-by: kustomize
  annotations:
    generated-by: kustomize
vars:
  - name: NAMESPACE
    objref:
      apiVersion: v1
      kind: Service
      name: ims-api-gateway
    fieldref:
      fieldpath: metadata.namespace