spring:
  datasource:
    url: jdbc:postgresql://postgres-prod.ims.internal:5432/ims_workflow_prod
    username: ${DB_USERNAME:ims_prod}
    password: ${DB_PASSWORD:ims_prod_password}
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 10000
      idle-timeout: 300000
      max-lifetime: 600000
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc.batch_size: 100
        order_inserts: true
        order_updates: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka-prod.ims.internal:9092}
    consumer:
      group-id: ${KAFKA_GROUP_ID:workflow-service-prod}
      auto-offset-reset: earliest
      properties:
        max.poll.records: 1000
        fetch.min.bytes: 2048
        fetch.max.wait.ms: 200
    producer:
      acks: all
      retries: 10
      batch-size: 32768
      buffer-memory: 67108864
      compression-type: snappy
      properties:
        linger.ms: 5
        max.in.flight.requests.per.connection: 1
        enable.idempotence: true
    listener:
      concurrency: 15
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:https://auth.ims.internal/}
          audience: ${JWT_AUDIENCE:ims-api-prod}
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:https://app.ims.internal}

server:
  port: ${SERVER_PORT:8083}
  tomcat:
    max-threads: 200
    min-spare-threads: 50
    max-connections: 20000
    connection-timeout: 5000
    accept-count: 500
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024

management:
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
      environment: production

logging:
  level:
    root: INFO
    com.ims: ${LOG_LEVEL:INFO}
    org.springframework: WARN
    org.hibernate: WARN
    org.camunda: INFO
  file:
    name: ${LOG_FILE:/var/log/ims/workflow-service-prod.log}
    max-size: 500MB
    max-history: 60
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [%X{correlationId}] - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [%X{correlationId}] - %msg%n'

camunda:
  bpm:
    admin-user:
      id: ${CAMUNDA_ADMIN_USER:admin}
      password: ${CAMUNDA_ADMIN_PASSWORD:prod_admin_password}
    job-execution:
      core-pool-size: 15
      max-pool-size: 30
      queue-capacity: 200
    metrics:
      enabled: true
      db-reporter-activate: true
    webapp:
      application-path: /camunda
      csrf:
        enabled: true
      header-security:
        xss-protection-enabled: true
        content-security-policy-value: "default-src 'self'"

feign:
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 1000
        loggerLevel: basic
      calculation-service:
        url: ${CALCULATION_SERVICE_URL:http://calculation-service-prod.ims.internal:8082}
  okhttp:
    enabled: true

workflow:
  locate:
    auto-approval:
      enabled: true
      max-quantity: 20000
      min-inventory-ratio: 2.0
      expiry-hours: 24
    manual-review:
      timeout-minutes: 60
      notification-enabled: true
    performance:
      thread-pool-size: 30
      queue-capacity: 300
  short-sell:
    validation:
      timeout-ms: 150
      cache-ttl-seconds: 300
      batch-size: 200
    performance:
      thread-pool-size: 50
      queue-capacity: 500
  scheduling:
    cleanup-expired-locates: '0 0 * * * *'
    process-pending-validations: '0 */2 * * * *'
    health-check: '0 */5 * * * *'

resilience4j:
  circuitbreaker:
    instances:
      locateWorkflow:
        registerHealthIndicator: true
        slidingWindowSize: 100
        minimumNumberOfCalls: 20
        permittedNumberOfCallsInHalfOpenState: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: '30s'
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: '5s'
      shortSellWorkflow:
        registerHealthIndicator: true
        slidingWindowSize: 100
        minimumNumberOfCalls: 20
        permittedNumberOfCallsInHalfOpenState: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: '30s'
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: '5s'
  retry:
    instances:
      locateWorkflow:
        maxAttempts: 3
        waitDuration: '500ms'
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
      shortSellWorkflow:
        maxAttempts: 3
        waitDuration: '100ms'
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
  ratelimiter:
    instances:
      locateWorkflow:
        limitForPeriod: 1000
        limitRefreshPeriod: '1s'
        timeoutDuration: '500ms'
      shortSellWorkflow:
        limitForPeriod: 2000
        limitRefreshPeriod: '1s'
        timeoutDuration: '150ms'
  bulkhead:
    instances:
      locateWorkflow:
        maxConcurrentCalls: 100
        maxWaitDuration: '500ms'
      shortSellWorkflow:
        maxConcurrentCalls: 200
        maxWaitDuration: '150ms'

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false